# Generated by Django 3.0.7 on 2020-06-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available_places', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['user_id'], name='user_surveys_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(check=models.Q(available_places__gte=0), name='available_places_is_a_whole_number'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey_id', 'user_id'], name='user_survey_responses_idx'),
        ),
    ]
